# Generated by Django 5.2 on 2026-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.RemoveField(
            model_name="location",
            name="address",
        ),
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(
                default="",
                help_text="Branch code (e.g., HUB, FM)",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this branch is active"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Branch name (e.g., Swahilipot Hub, Swahilipot FM)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
