# Generated by Django 5.2 on 2026-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload your profile picture",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
