# Generated by Django 5.2 on 2026-03-05 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_location_options_remove_location_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_number",
                    models.CharField(
                        help_text="Unique pass identifier", max_length=20, unique=True
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(help_text="Full name of visitor", max_length=100),
                ),
                (
                    "visitor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Visitor email (optional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "visitor_phone",
                    models.CharField(
                        blank=True,
                        help_text="Visitor phone (optional)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("contractor", "Contractor"),
                            ("delivery", "Delivery"),
                            ("staff", "Staff"),
                            ("other", "Other"),
                        ],
                        default="guest",
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company or organization (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("purpose", models.TextField(help_text="Purpose of visit")),
                (
                    "host_name",
                    models.CharField(help_text="Person being visited", max_length=100),
                ),
                (
                    "host_department",
                    models.CharField(
                        blank=True,
                        help_text="Department of host (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time of check-in"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, help_text="Time of check-out", null=True
                    ),
                ),
                (
                    "expected_departure",
                    models.DateTimeField(
                        blank=True, help_text="Expected departure time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes (optional)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this pass",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Branch location (auto-inherited)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passes",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor Pass",
                "verbose_name_plural": "Visitor Passes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "status"],
                        name="reception_p_locatio_ff993d_idx",
                    ),
                    models.Index(
                        fields=["pass_number"], name="reception_p_pass_nu_0ccd7b_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="reception_p_created_dd39dd_idx"
                    ),
                ],
            },
        ),
    ]
