# Generated by Django 5.2 on 2026-03-05 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_location_options_remove_location_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Visitor's full name", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary phone number", max_length=20),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID or passport number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Company or organization",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Visitor",
                "verbose_name_plural": "Visitors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(help_text="Purpose of visit", max_length=200),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="Person being visited",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "host_department",
                    models.CharField(
                        blank=True,
                        help_text="Department of host",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("check_in_time", models.DateTimeField(help_text="Time of check-in")),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, help_text="Time of check-out", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the visit",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="core.location",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="visitor.visitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "Check In"),
                            ("CHECK_OUT", "Check Out"),
                            ("CREATE_VISITOR", "Create Visitor"),
                            ("UPDATE_VISITOR", "Update Visitor"),
                            ("CANCEL_VISIT", "Cancel Visit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context about the action",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="visitor.visit",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="visitor.visitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["visitor", "location", "status"],
                name="visitor_vis_visitor_edb6e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["visitor", "status"], name="visitor_vis_visitor_5b9c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["check_in_time"], name="visitor_vis_check_i_92ca04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="visitor_aud_user_id_c8ff47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="visitor_aud_action_7dbd36_idx"
            ),
        ),
    ]
